swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "0.1.0"
  title: Social Media Comment Generator Interface API
consumes:
  - application/json
produces:
  - application/json

basePath: /v1
# Paths supported by the server application
paths:
  /getComment:
    get:
      operationId: src.methods.generate_comment_endpoint
      tags:
        - Comment Generation
      summary: Generate text from a social media post and extract it's topic and entities in the post. 
      parameters:
        - in: query
          name: post
          type: string
          required: true
      responses:
        200:
          description: ok